### ISSUE TITLE
Authentication fails for outlook.com account

### ISSUE THREAD

**Issue by wigster** [RogerSelwyn/O365-HomeAssistant#100]
Hi,

Just trying your integration for the first time. I have an outlook.com account with a microsoft365 family subscription and 2FA authentication. I have logged out and in to the account after setting up the app in the Azure Portal as a Personal Account. I also have a work account, which is logged into on my machine, but I am not touching that otherwise.

I have followed the instructions to set up the app, the permissions, etc. When I click on the Link O365 account link in HA I get to choose my outlook.com account, the page is rediected to the microsoft online URI, but the page is blank the URL contains an error:

```
https://login.microsoftonline.com/common/oauth2/nativeclient?error=invalid_request&error_description=The%20request%20is%20not%20valid%20for%20the%20application%27s%20%27userAudience%27%20configuration.%20In%20order%20to%20use%20/common/%20endpoint%2c%20the%20application%20must%20not%20be%20configured%20with%20%27Consumer%27%20as%20the%20user%20audience.%20The%20userAudience%20should%20be%20configured%20with%20%27All%27%20to%20use%20/common/%20endpoint.&state=Dcx48R40COGcvhsJFFmY3zM25LVoMU
```
 When I log back into the Azure Portal I get this (couldn't copy the text)
 
<img width="247" alt="image" src="https://user-images.githubusercontent.com/10956987/208668455-302e441b-c0a3-4342-b7cd-ab9b198df214.png">

Is there anything I can try?

**Comment by RogerSelwyn** [comment]
It sounds like your two acco8unts are getting mixed somehow. Follow the instructions carefully, I would recommend you use `Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)` for the supported account types since you are using an outlook.com account (you cannot use `Personal Microsoft accounts only` as noted in the instructions. Make sure you have logged out of all MS accounts in your browser before logging in to create the Azure App. Also, since this is a personal account, note the sensors that will not work for you, so do not enable them in your config.yaml

**Comment by wigster** [comment]
OK, that was my bad for reading your prerequisites wrong in the part on the account type. I could not parse the parentheses and chose "only Personal account" instead of the option including a personal account. I've managed to get it to work now! Thanks

**Comment by RogerSelwyn** [comment]
Thanks, I've adjusted the documentation to try to make that clearer.
