### ISSUE TITLE
To Do List Card 

### ISSUE THREAD

**Issue by Daniel100111** [RogerSelwyn/O365-HomeAssistant#105]
If I may ask one more question please.

Do you have a To do List / Task card you can share please.

- Add tasks.
- Update tasks.
- Delete tasks.
- Add notes 

Many thanks.

**Comment by RogerSelwyn** [comment]
Sorry I don't have cards to perform the functions, not sure I know how to do that. The services are available, but you would need to do your own card.

**Comment by RogerSelwyn** [comment]
I think you need to understand the difference between frontend and backend. The integrations I write are back-end components that provide data to the front-end, and provide side services that the front-end can call to do things. The just provide and receive data, they don't format for display. You will notice all dates the integration provides are in UTC, because it has no knowledge of where the user will view it from in the front-end.

I don't get involved in the front-end and the writing of cards or whatever. This is purely because I don't have the time or desire to be involved in all aspects. I imagine a card can be designed to take the inputs, and act on them, but I won't be writing one.

This may sound negative, not intended to be, just to set scope of what I get involved in.

**Comment by Daniel100111** [comment]
Thank you Roger

Noted. Thank you for the work done on this integration. Really appreciate it.

Regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
