### ISSUE TITLE
Group (Team/Shared) to do list interrogation 

### ISSUE THREAD

**Issue by Daniel100111** [RogerSelwyn/O365-HomeAssistant#109]
Have a request please.

Will it be possible to add group “To do list”  interrogation.

We have external user adding to the list and want to make is visible in HA. 

Thank you for the great work on this.

Regards

**Comment by RogerSelwyn** [comment]
Sorry, it's not clear what you mean by ToDo group.

**Comment by Daniel100111** [comment]
Shared lists.

**Comment by RogerSelwyn** [comment]
Please find the relevant apis in the ms graph api - https://learn.microsoft.com/en-us/graph/api/resources/todo-overview?view=graph-rest-1.0

**Comment by RogerSelwyn** [comment]
This from 2020 says they aren't available in the api - https://github.com/microsoftgraph/microsoft-graph-docs/issues/7041. Not clear if they are now.

**Comment by Daniel100111** [comment]
Task:

Group.Read.All, Group.ReadWrite.All

**Comment by RogerSelwyn** [comment]
That is a permission not an api call. I need the api link.

**Comment by RogerSelwyn** [comment]
I suspect you mean this - https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/planner-overview.md. This is tasks within a (bucket within a ) plan within a group. https://learn.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-1.0

At this time I am unlikely to start trying to build up any type of planning support, because it won't just be displaying the tasks, but the intelligently creating and maintaining the tasks in the plan and I can see at a glance that it is complex. And then maintaining the buckets and the plans, etc, etc.

Maybe at some point in the future,  but I have other projects I'm engaged in at this time.

**Comment by Daniel100111** [comment]
Will this work? (Nee to all of this)

https://developer.microsoft.com/graph/graph-explorer/?request=me%2FmemberOf%2F%24%2Fmicrosoft.graph.group%3F%24filter%3DgroupTypes%2Fany(a%3Aa%2520eq%2520%27unified%27)&version=v1.0

**Comment by RogerSelwyn** [comment]
> Will this work? (Nee to all of this)
> 
> https://developer.microsoft.com/graph/graph-explorer/?request=me%2FmemberOf%2F%24%2Fmicrosoft.graph.group%3F%24filter%3DgroupTypes%2Fany(a%3Aa%2520eq%2520%27unified%27)&version=v1.0

Please see my previous comment
