### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by surfingbytes** [RogerSelwyn/O365-HomeAssistant#128]
1/ Set up both Home Assistant + Outlook to some timezone (+1 in my case).
2/ In Outlook, add event without timezone specified.
3/ The event will show wrong by "minus timezone offset" in HA/this integration. That means even set to 4pm will appear as 3pm in HA.

**Comment by RogerSelwyn** [comment]
Where are you seeing the time is wrong? In the HA Calendar or in Developer Tools/States.

**Comment by surfingbytes** [comment]
That in turn means the time is wrong in morning announcement, because there is wrong value in the entity:

            {%- for event in state_attr('calendar.calendar_personal', 'data') -%}
              {% if not event.all_day %}
                From {{ event.start.strftime('%-H:%M') }} to {{ event.end.strftime('%-H:%M') }}
              {% endif %}
              {{ event.summary }}.
            {%- endfor -%}

**Comment by RogerSelwyn** [comment]
Times shown in their are in UTC because the integration does not know what the display timezone is. Please consider that a home assistant instance may be viewed from multiple timezones with times requiring to be 'shown' in as being different in each timezone. This translation is handled by Lovelace front-end, however Lovelace does not do any translation to items in developer tools/states.

If you look in Calendar they will show correctly, which is why I asked the question, since Lovelace will translate them for display.

**Comment by RogerSelwyn** [comment]
You will notice that the times in the data attribute show +0000, which means they are displayed in UTC. You need to translate to your own timezone which would be +0100

**Comment by surfingbytes** [comment]
Thank you for looking into it. For anyone running into the same issue, as_local() has to be called. This is how I updated the template:

{%- for event in state_attr('calendar.calendar_personal', 'data') -%}
          {% if not event.all_day %}
            From {{ as_local(event.start).strftime('%-H:%M') }} to {{ as_local(event.end).strftime('%-H:%M') }}
          {% endif %}
          {{ event.summary }}.
        {%- endfor -%}
