### ISSUE TITLE
Start and end offset are ignored

### ISSUE THREAD

**Issue by maxalbani** [RogerSelwyn/O365-HomeAssistant#13]
I report a problem also present in the original version but never solved.

Start and End offset are not considered by the sensor.
I configured end offset to 120 to have the events of the next 5 days in the sensor data attribute but it is always shown and only the current day.
I use the data attribute with templates to create my own custom sensor with the next event.
You can control?

Thanks!

**Comment by RogerSelwyn** [comment]
Please can you post your config, because I cans see this works for me as below:

```
- cal_id: ############################################
  entities:
  - device_id: Bookings
    end_offset: 672
    name: Bookings
    start_offset: 0
    track: true
```
When I look at the calendar.bookings entity, I can see it shows a Message attribute with other attributes for the first entry, then a Summary attribute plus associated other attributes for each of the other entries within the time period. These change when I change the end_offset.

Looking at it some more, when I change the end_offset to exclude the current event (mine are typically five days long), the Message attribute still shows current event, and the Summary attributes change to show only future events.

Given I didn't design this, and there are many people use it, I wouldn't want to change the way the data is presented, but it seems to reflect the way the offsets are configured.

**Comment by RogerSelwyn** [comment]
I'm afraid that since it has been like this for along time, and there are hundreds of people using it, I don't want to change the structure of the output data. My suggestion would be that you write your sensor to read the first summary attribute. To me this looks like a yaml structure which you should be able to extract the relevant information from.

**Comment by maxalbani** [comment]
> Temo che poiché è così da molto tempo e ci sono centinaia di persone che lo usano, non voglio cambiare la struttura dei dati di output. Il mio suggerimento è di scrivere il sensore per leggere il primo attributo di riepilogo. A me questa sembra una struttura yaml da cui dovresti essere in grado di estrarre le informazioni rilevanti.

Yes, I certainly could, but the summary only shows it if there was an event during the day, otherwise no. And this is a bug in my opinion

**Comment by RogerSelwyn** [comment]
Sorry, I'm not sure what you mean by the summary only shows if there is a bug during the day, it shows the full set of attributes. 

We may end up agreeing to differ on whether it is a bug or not.

**Comment by maxalbani** [comment]
Maybe I can't explain myself well in English.
I refer to [this problem](https://github.com/PTST/O365-HomeAssistant/issues/61) also reported by other users.
It is really a shame that this very useful component does not work as it should.

**Comment by maxalbani** [comment]
Ok thanks anyway for the time you have dedicated to me

**Comment by RogerSelwyn** [comment]
I'll see if I can create a sensor, not easy so dar. I know I could do it in Node Red, but you may no what to use that.

**Comment by maxalbani** [comment]
I am familiar with node-red but I only use it in rare cases. I prefer to work things out in Home Assistant with templates.
Thanks anyway, I change my custom sensor to read the summary instead of the message attribute.

**Comment by RogerSelwyn** [comment]
OK, in case you can't get the attribute because it is an array, the below will work.

```
- platform: template
  sensors:
    booking_event_name:
      friendly_name: "Event Name"
      value_template: "{{ state_attr('calendar.bookings', 'data')[0].summary }}"
```

**Comment by maxalbani** [comment]
> OK, in case you can't get the attribute because it is an array, the below will work.
> 
> ```
> - platform: template
>   sensors:
>     booking_event_name:
>       friendly_name: "Event Name"
>       value_template: "{{ state_attr('calendar.bookings', 'data')[0].summary }}"
> ```

yes, i know ;)

look here, today I have no events in the calendar and after restarting home assistant the summary is not there.

If I add a dummy event for today after a while it faithfully shows me the summary based on my end offset. But if there is no event today it shows nothing. Do you agree with me that this shouldn't happen?

![Schermata 2022-01-10 alle 17 43 31](https://user-images.githubusercontent.com/46787665/148804440-ed422b22-cedf-448e-9b45-e2429fb056d6.png)

**Comment by RogerSelwyn** [comment]
OK, I'll take a look tomorrow.

**Comment by RogerSelwyn** [comment]
I can see where it is happening, but need to figure whether I can fix it. This code is strange....

**Comment by maxalbani** [comment]
> I can see where it is happening, but need to figure whether I can fix it. This code is strange....

I am a developer, I would gladly help you but I don't know python well unfortunately

**Comment by RogerSelwyn** [comment]
Please try this release - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v2.2.8b1

This should always include any items in the date range as Summary items.

**Comment by maxalbani** [comment]
> Please try this release - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v2.2.8b1
> 
> This should always include any items in the date range as Summary items.

great, it works!
thank you

**Comment by maxalbani** [comment]
sensor fixed with summary ;)

![Schermata 2022-01-10 alle 20 51 19](https://user-images.githubusercontent.com/46787665/148830018-32b5bda8-ada2-47ba-8a89-4d7e155f0bcf.png)
