### ISSUE TITLE
Configurable "Upcoming Tasks" from Todo

### ISSUE THREAD

**Issue by akshaya-a** [RogerSelwyn/O365-HomeAssistant#130]
I don't know about others, but I use ToDo for planning more than just overdue tasks. So i frequently find the overdue_tasks attribute not very useful as I end up parsing the all_tasks anyway.

A simple approach might be to expose a configuration where users can provide a timedelta (say, 1 or 2 days by default) and including them as an attribute here:
https://github.com/RogerSelwyn/O365-HomeAssistant/blob/master/custom_components/o365/classes/taskssensor.py#L74

Curious to hear your thoughts on this!

**Comment by RogerSelwyn** [comment]
Sorry, I don’t understand what you mean. Do you mean to filter tasks that are within a certain period (similar to how the calendar works)? If not, where do you see a delta being provided?

**Comment by akshaya-a** [comment]
Yes exactly - in the dashboards where I present tasks, I generally want to show tomorrow, today, and overdue tasks, not just the overdue ones

**Comment by RogerSelwyn** [comment]
I'll have a look at see if the api supports it. If not, there really isn't any benefit in terms of reduction of data retrieval.  

I also see challenges in what you mean by a day. Do you mean 24 hours? Or do you mean start of the previous day? If start of the previous day, in what timezone? The integration is timezone neutral and has no idea what timezone the data is being viewed in (hence it works in utc). So if your user is in PST, will they be happy that the start of the previous day in UTC is 16 hours ago in PST?

These are things you can handle in a template because you can convert to your users local time before doing a filter, something that simply cannot be done by the integration, much as everyone would like it to.

**Comment by RogerSelwyn** [comment]
I've had a look and it is possible to filter based on dueDateTime, though it might need a change in the underlying library to achieve that. 

Have you got any thoughts on the issues I expressed about a 24h/1 day time windows?

**Comment by akshaya-a** [comment]
great! I think the integration is already struggling under the load of retrieving all my calendar + task data, I see many timeouts, so I agree with you that this is mostly worth it for reduction of queried data.

If i were designing it, it feels most natural to take a "timedelta" - tasks that are X time ahead of now.  Therefore I think the UTC/locale issue sorts itself out (the integration looks forward X time without zoneinfo) and the frontend can render in the user's locale.

That said, I'm sure eventually someone will want "all tasks in the next few days", though I think it's mitigated by a couple factors:
1. outlook allows you to schedule tasks onto your calendar by dragging them on, and if I were thinking about tasks day-oriented, I would have done this.
2. there's *still* the template fallback - of course, you'd have to believe my scenario is more common than this for that argument 😄 

Of course, happy to hear alternatives

**Comment by RogerSelwyn** [comment]
Required pulled request has been raised - https://github.com/O365/python-o365/pull/952

**Comment by RogerSelwyn** [comment]
Awaiting release of python-o365 module with required due date support

**Comment by RogerSelwyn** [comment]
Unfortunately this is still waiting a release of the o365 python module.

**Comment by RogerSelwyn** [comment]
This should be enabled with this release - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.3.2
