### ISSUE TITLE
Teams Chat Send Message Support

### ISSUE THREAD

**Issue by veilofsecurity** [RogerSelwyn/O365-HomeAssistant#143]
It would be great to have a notify service for Teams Chats (not to be confused with posts in a channel) in addition to the existing email function. I have a couple automations that would be really handy to inject a message into a group chat for notification and discussion.

**Comment by RogerSelwyn** [comment]
I’d need to think about this because it is way more complex than sending an email. At the moment you only know the chat id (which is the identifier you need) for the last chat, so I’d have to fetch all recent chats for you to then pick one you want to send a message on. The danger is this becomes too big a data burden because currently there isn’t a way to just get the latest messages for a conversation. 

If you can refine how you think this would work I’ll think on it some more.

**Comment by veilofsecurity** [comment]
It looks like the chat-list endpoint doesn't return messages so I'm not sure I follow you. https://learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0

Here is a sample where a product is doing similar and to get chat ID they can accept an ID or Name of the chat, maybe that would be helpful?: https://github.com/demisto/content/blob/dbc651f9c62d8a4c948e9f19f493ce9b3b17ed99/Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py#L855

**Comment by RogerSelwyn** [comment]
The O365 integration uses the python-O365 python module - https://github.com/O365/python-o365

This retrieves a list of chats via this api call - https://learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&tabs=http - `GET /me/chats`

To get date/time of latest message, it loops through the list of chats using this call - https://learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&tabs=http - `GET /me/chats/{chat-id}/messages`

To send a message in the chat it will use this call - https://learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&tabs=http - `POST /chats/{chat-id}/messages`

So the send message requires 'chat-id', which is almost certainly not available within HA because currently the code only returns chat_id for latest message.

So potentially this could be done by you providing a unique chat name, which can then be used to as a filter to `GET /me/chats` (which is what the code you linked to does), or if you happen to know the chat_id (not sure if you can find it elsewhere), which can then be used to send a message.

What identifier do you wish to use, options seem to be a **unique** name or id sourced from outside the integration, because currently it doesn't provide a list of either.

**Comment by RogerSelwyn** [comment]
Or if one-one, provide a username.

Basically the logic you linked to. But all need chat_id

**Comment by veilofsecurity** [comment]
But why does a list of messages need returned? You only need chat_id to send a message which doesn't need to know anything messages. I don't see where get_my_chats in python-O365 is iterating through messages, it appears to page through all chats but also looks to support a limit.

Could you expose a sensor that checks for the 10 most recent chats with get_my_chats and just lists name:type:id or something?

I also wouldn't be opposed to a requirement to obtain chat_id outside of the integration but not sure if you want that user experience. Maybe just point people to the Powershell documentation: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.teams/get-mguserchat?view=graph-powershell-1.0

**Comment by RogerSelwyn** [comment]
Reading through the links I posted I don’t think I need to receive all messages, I could just provide users a list of chat_ids in the data attribute as you suggest

**Comment by RogerSelwyn** [comment]
Been looking at this:

- Easy to get a list of chat_ids, I've already got those anyway
- There is no topic for a oneOnOne chat (to be used for a later retrieval of a chat_id) - The link you provided uses username to get chat_id, and no username is retrieved as part of the call I make, I get this content - https://learn.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0#properties.
- To get some sort of user identifier I need to retrieve that chat messages (the python library currently does not have `get_chat`, only `chat_get_messages`). This will then retrieve `from_id` and `from_display_name`, I imagine the from_id can then be used to do the `create_chat` to get the chat_id. However, it doesn't look that call is present in python-o365.
- I might be able to get the members though (as you can tell I'm logging my thoughts...).
- For group chats I should get the topic, which I could then display and re-retrieve chat_id using it.

**Comment by RogerSelwyn** [comment]
And for a group chat it doesn't necessarily have a topic.

**Comment by RogerSelwyn** [comment]
So in summary:

- With an extra call once per reboot on a `oneOnOne` I can get a list of user_ids and names
- With an extra call on every update (because members might change) for a `group` I can get a list of user_ids and names
- I may be able to get topic on a call I'm already doing for a `group`, but I imagine this might be rare. So there is no real identifier for a group chat apart from list of members

Interested in your thoughts on this....

**Comment by veilofsecurity** [comment]
Interesting. Definitely disappointing Microsoft doesn't include some sort of meaningful identifier in list chats. Listing members with get_members seems like it should work to identify a chat though. 

In my use of Teams, we almost always set a topic for group chats that will be used for any length of time. For ad-hoc chats with a group that wont hang around we might not but for the most part our groups have a topic.

So something like:
chats = get_my_chats
for each chat in chats -> get_members

Then a sensor with chat_id:[members]? Seems like that should work. Bonus use case is someone could trigger automation if group membership changes.

**Comment by RogerSelwyn** [comment]
At the moment I have added a data attribute to the existing chat sensor which has an array of:

- chat_id - the id we need
- chat_type - oneOnOne/group/meeting
- members - comma separated list of names
- topic - if available on group chat

Need to add the service another day.

**Comment by RogerSelwyn** [comment]
Currently limited by first 20 chats (strangely for my list of 4 chats, to only retrieved the first 2 when I set limit to 10). Re-retrieves member lists for non oneOnOne.
