### ISSUE TITLE
How to integrate todo tasks into HA

### ISSUE THREAD

**Issue by chimph** [RogerSelwyn/O365-HomeAssistant#149]
As per title. I've successfully brought the integration into HA but I'm at a bit of a loss as how to display and interact with these tasks. I thought maybe the shopping list integration would help me here but it doesnt allow for adding entities. Thank you

**Comment by RogerSelwyn** [comment]
Sorry, I can’t really advise on this.l, I don’t use it myself but added it because I had a request raised. You might find some things to build on at the link below, which is a previous integration that just did Tasks but became unsupported. 

https://github.com/black-roland/homeassistant-microsoft-todo
