### ISSUE TITLE
Events - Tasks - External completion does not raise event

### ISSUE THREAD

**Issue by Caff522** [RogerSelwyn/O365-HomeAssistant#160]
While the New Task event is fired when a task is created in an external app (such as the Microsoft To-Do app) or via the integration, marking a task as completed in an external app does not seem to fire the Completed Task event; the event is only fired when an event is marked complete via the integration. 

Thank you.

**Comment by RogerSelwyn** [comment]
I note I have this `o365_completed_task - Task marked complete either by the O365 integration or via some external app` so it should do it. I'm away at the moment and take a look when I get back

**Comment by RogerSelwyn** [comment]
Do you have `show_completed` enabled in tasks.yaml for the task_list you are completing externally? Sorry, there is nothing majorly clever here, it is just looking at the completed date/time when retrieving the tasks, and seeing if it is after the last time they were updated. If you don't have it configured to pull back completed items, it doesn't have a completion date to work from (because they only ones retrieved will be incomplete).

**Comment by Caff522** [comment]
Thanks so much for clarifying! Looks to be working. Much appreciated.
