### ISSUE TITLE
Shared mailbox calendar

### ISSUE THREAD

**Issue by stre1026** [RogerSelwyn/O365-HomeAssistant#166]
Thanks for this great integration!

Has anyone gotten calendars to work that are part of a shared mailbox? I've granted proper permissions in Azure and managed to find the calendar ID of the shared mailbox calendar. The user of course has access to the shared mailbox. I've added it as another line in my o365_calendars yaml file but I can't get it to work. From the documentation, it looks like this should be possible but I'm struggling to figure it out. The user of course has access to the shared mailbox.

**Comment by RogerSelwyn** [comment]
Pretty sure when I created a shared mailbox, and then gave a user permissions to Read and Manage, I just had access. But I notice that only one of my shared mailboxes appears in my list of calendars, so I'll have to investigate what is going on.

Buried in something else at the moment, but I'll get to it.

**Comment by RogerSelwyn** [comment]
The way I got access to the shared calendar was to give permissions via MS 365 Admin Center (I granted `Read and manage permissions` plus `Send as permissions` to my main O365 account. 

This allowed me to add the account to `Shared with me` dialogue in Outlook (Mac) and make the calendar (and everything else available). 

Then in Outlook I accessed the permissions of the calendar and granted myself `Edit` permissions to the calendar. This then made it visible in this api call in Graph - https://graph.microsoft.com/v1.0/me/calendars

Please give this a go, because programmatically it makes it much easier and neater than you having to manually add a calendar in calendars.yaml, and then me coding to retrieve it from the graph call you provided. I know it is an extra user step, but a quick look at the api says there is no way to retrieve this list of calendars that have been shared to a user.

**Comment by stre1026** [comment]
Hmm. OK. I had most of this done already because that's how I use the calendar now. The only part I hadn't done is apply the permissions directly on the calendar. I just did that. It's still not showing up but I will give it some time. Changes to a Microsoft Tenant aren't always instant.

**Comment by RogerSelwyn** [comment]
You would need to reboot HA, (or run the scan for calendars service).

**Comment by stre1026** [comment]
It's still not showing up in the graph, but once it does, I will then restart HA.
________________________________

**Comment by RogerSelwyn** [comment]
When it appears in Graph you should be good. Came up in there straightaway for me I think. Got friends round, so would need to undo and redo it to check.

**Comment by stre1026** [comment]
That worked! You learn something new every day. I've been an Exchange admin for over 20 years and I never knew that adding a shared calendar in Outlook adds a link to your personal account. This actually solves another issue I have at work as well so thank you for that!
________________________________
