### ISSUE TITLE
Calendar Summary entries as Attibutes

### ISSUE THREAD

**Issue by b-0s** [RogerSelwyn/O365-HomeAssistant#17]
Hello

Thanks for this wonderfull work done on the O365 

Any chance to have all the Summary sub entries as attributes for the calendar entity.
It is very difficult to work with the sole DATA attributes.

**Comment by RogerSelwyn** [comment]
I believe it is structured like that for a reason. I note from issues raised on the original author's Github, (given that I only took it on to keep it working on newer versions of HA), that he didn't want to change the structure of the Data attribute because he wasn't sure of the downstream impacts.

I'm not sure what structure you are thinking of, but the data attribute is an array and I think it should be relatively easy to work with. I don't use the native HA automation capabilities, I use Node Red, which sees it as an array object.

<img width="511" alt="Screenshot 2022-02-07 at 09 27 31" src="https://user-images.githubusercontent.com/7115783/152761325-918519b6-62e6-4117-a527-5b5b1c2984a4.png">


You may wish to look at this comment on a previous issue which was me trying to figure out how to parse the data attribute - https://github.com/RogerSelwyn/O365-HomeAssistant/issues/13#issuecomment-1009095758

If you can also provide more detail on what you are looking for specifically, that would help. It might be possible to break out the attributes for the current event, but since the data attribute also holds future events I don't that could (or should) be changed.

**Comment by b-0s** [comment]
Thank you for your kind reply.
Indeed you are right. It is easy to work with. Particularly when you have the right syntax (thanks again for the link).
But as a matter of fact, it had a bit of a suggestion to be on par with Google Calendar. 
But that is totally fair.
