### ISSUE TITLE
Not seeing Teams presence change

### ISSUE THREAD

**Issue by loryanstrant** [RogerSelwyn/O365-HomeAssistant#20]
How often does this read the Teams presence data from Graph?
I'm not seeing any presence data come through at all.
Calendar is working fine however.

Any ideas?

**Comment by RogerSelwyn** [comment]
Have you add the relevant configuration to your config.yaml? Is so, what errors are shown in the logs?

**Comment by loryanstrant** [comment]
Config has definitely been added as per the example, unless I'm missing something?
![image](https://user-images.githubusercontent.com/51473494/155280091-f331c411-520c-46db-b7c8-1452eddb9674.png)

**Comment by RogerSelwyn** [comment]
Are there any errors in the logs? And did you grant the relevant permission on the MS Graph api? In theory if you didn't you will get an error in the log.

**Comment by loryanstrant** [comment]
Definitely allowed in Azure AD:
![image](https://user-images.githubusercontent.com/51473494/155280567-30d555d4-9504-44c9-920d-70eddf82c222.png)
Not seeing anything in the logs.

**Comment by RogerSelwyn** [comment]
I’m away from home so can’t setup any extra debugging for you, so it will need to wait until Sunday at the earliest. I forget what debugging is in there, but you can always capture it in your logs and it might give a clue.

**Comment by loryanstrant** [comment]
All good, thanks, I appreciate it.
BTW I can see in Azure AD that the app is connecting and requesting the information successfully.
Is there a way to query the sensor to tell me what value it has received? I'm just using a sensor card at this point.

**Comment by RogerSelwyn** [comment]
I just look in Developer Tools. I haven’t configured an interval on it so it will be whatever the default is for HA which I think is every few seconds. 

If you know any Python (and even if you don’t) you can add a debug log at the end of the sensor.py (because that is where the update code has been added) to show the value of the data being returned. If you never get anything in the log then it is never being called.

**Comment by RogerSelwyn** [comment]
OK, I've done a whole lot of work on it this morning, reviewing how permissions are requested and what permissions are requested. I've set it so it always requests base permissions:

- Offline Access
- User Read
- Calendars Read/Write
- Mail Send

Optionally it will request:
- Mail Read
- Presence Read

It requests the Calendars Write and Mail Send because there are services that use these permissions, and I have no way of identifying if they will be used or not at startup time. It does check them when a user calls the service, so there aren't great big failures in the logs if the correct permissions aren't provided.

The integration will function with just, so when it checks for those permissions it will also check if any of the higher levels have been granted (e.g. Calendar ReadWrite instead of Calendar Read):
- User Read
- Calendar Read
- Mail Read (Optional)
- Presence Read (Optional)

I've stopped it asking for Mail ReadWrite because I can't find any functionality that requires Write (but it will still work if ReadWrite has been granted). I've also stopped it asking for 'Shared' because I believe it only access the configured account. It's possible I may be wrong on either of these.

If you have any thoughts it would be appreciated.

Happy to provide a beta if you want to test.

**Comment by loryanstrant** [comment]
Awesome, thanks.
I modified the file to adjust the permissions ![Screenshot_20220228-233936_Home Assistant.jpg](https://user-images.githubusercontent.com/51473494/155984966-a4c043d7-5545-420d-b7a7-18c2884f1795.jpg)

**Comment by loryanstrant** [comment]
This seems to be working perfectly now, and I have it connected to some automations now.
Am going to write a blog post (and will credit you and this fork), and have some videos to go with it of it changing my LED lights on presence change, as well as the Fully Kiosk Browser URL on the tablet outside my study.

Also, the alt-auth model is the best scenario as it uses a generic redirect URL in the service principal, so multiple people in the org can use it.

**Comment by RogerSelwyn** [comment]
I'd already removed 'email' and 'profile' in my code already submitted,

**Comment by loryanstrant** [comment]
Yeah, I get that.
Any chance you can make the minimum required permissions not include "write" please?
As a person who specialises in M365 Governance (I live and breath it), I generally discourage my clients from anything having write access unless absolutely necessary.

**Comment by loryanstrant** [comment]
> I'd already removed 'email' and 'profile' in my code already submitted,

Will check out the code tomorrow.

**Comment by RogerSelwyn** [comment]
I'm just adding a setting which will default to True (so the old world doesn't break), but can be set to False to disable update permissions.

**Comment by RogerSelwyn** [comment]
I plan to release this in the next few days. Would be good to read the blog when you get it done. Thanks :-)

**Comment by loryanstrant** [comment]
Super, will do it probably today.
Will tag you on Twitter when I do.

**Comment by loryanstrant** [comment]
Here you go: https://www.loryanstrant.com/2022/03/04/microsoft-teams-home-assistant-graph-take-your-presence-to-the-next-level/

**Comment by RogerSelwyn** [comment]
Thanks 😀

**Comment by RogerSelwyn** [comment]
Fixed with - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v2.4.0
