### ISSUE TITLE
App doesn't request presence information

### ISSUE THREAD

**Issue by loryanstrant** [RogerSelwyn/O365-HomeAssistant#21]
When trying to auth an account, presence data is not requested (especially when using alternate authentication):
![image](https://user-images.githubusercontent.com/51473494/155283775-fe63c80b-4383-4f87-ab14-6633af2b24c5.png)

**Comment by RogerSelwyn** [comment]
The 'App' is the one you created in the Azure portal as detailed in how to get your client secret.The integration itself I don't believe requests permissions at all, rather it requires that you have configured the permissions correctly. For me, my permissions look like this on the API Permissions tab of the App registration. You say you have set permissions on the Azure AD, but that sounds different to here (I may well of course be wrong), certainly your screenshot in the other issue has a different layout.

<img width="913" alt="Screenshot 2022-02-23 at 09 17 39" src="https://user-images.githubusercontent.com/7115783/155291316-0337a45f-f76b-4b5b-8fed-af0672cb431d.png">

I add my usual caveat here, I'm caretaking this integration because otherwise it would not work anymore and the previous maintainer had archived it. I'm slowly learning, but each time there is a new type of problem at the MS end of it, it takes time figure out what is going on.

**Comment by RogerSelwyn** [comment]
Looks like I may be wrong. Try modifying cont.py around line 100 to add Presence.Read.

**Comment by RogerSelwyn** [comment]
I'm looking at the code around checking permissions. It needs sorting out.... I'll spend a couple of days (if I have time) at the start of next week making it more intelligent. I've not looked at it before :-(

**Comment by loryanstrant** [comment]
Not a problem.
The screenshot I pasted is from when you use the alternate auth method.
Instead of using the app registration, the alt ath method creates a service principal in Azure AD which is what requested the permissions and missed Presence.Read.

I'm not a dev, but I know my M365 and it's quirks. :)

Will make that modification tomorrow and give it another go.

Thanks

**Comment by loryanstrant** [comment]
Just a note on permissions...
I did see it come up earlier when it detected that I'd reduced the permissions.
I get the logic, but there's things in there that I don't want the app to be able to do against a corporate environment - such as write to objects or send on behalf of others.
It would be nice if while you're reviewing it, there was a way to out a flag/switch/toggle into the config that ignores a reduced permission set.

It's only because I'm the admin of our tenant that I'm even allowing it with the current permissions. If it was one of my users or clients - I'd be telling them not to allow it in its current form. :)

**Comment by RogerSelwyn** [comment]
I intend to get it to retrieve the permissions, then validate they match the configured sensors/calendars and get it to authenticate if not. At the moment it is just 'does it have any permission', if it does then go ahead and enables sensor, if not ask for permissions.

I'd also aim to get it to build the permissions scope when authenticating against the requested sensors/calendars - at the moment it requests everything it might need, rather than what it does need. Not very 'Least Privilege', but it works because if someone then just configures what they want to give then it will work. 

All I have with me at the moment is a laptop, which I can remote into my home environment for emergencies, but this is relatively complex and I want my two big screens :-)

**Comment by loryanstrant** [comment]
Thank you for your efforts, they are greatly appreciated. :)

**Comment by loryanstrant** [comment]
Seems to be all working now after a restart this morning!
I modified the const.py to add Presence.Read and happy days.
Also modified the minimum sensors required to only have user.read and calendars.read so it would stop complaining. :-)
