### ISSUE TITLE
No task lists

### ISSUE THREAD

**Issue by williamg97** [RogerSelwyn/O365-HomeAssistant#249]
So this seems to be an issue with the graph API itself.

Long story short I originally was getting only the "Flagged Emails" list back from the extension even though i have over 20 lists in my app. I then used the Graph API explorer and confirmed the same - only the flagged emails list in the API response. 

Now when I turned "Flagged Emails" on then off in the Windows App it stopped returning any lists at all. See below:

![image](https://github.com/user-attachments/assets/fb462477-2114-4bbb-a01e-fa602423f9d1)

I then found this issue which told me to try the delta endpoint instead: https://learn.microsoft.com/en-us/answers/questions/594742/microsoft-graph-todo-api-doesnt-return-all-task-li

![image](https://github.com/user-attachments/assets/3d4ec271-f30a-4024-b057-81e8cc8ff0e8)

So clearly theres some issue with the actual API itself (maybe I have too many lists), but I thought it was worth creating this issue in case it would be better to use the delta endpoint instead?

**Comment by RogerSelwyn** [comment]
Hmm, not an easy one since all the calls are made in an external library 'python-o365'.  I probably won't get to look at it until the week after next.

**Comment by RogerSelwyn** [comment]
Thank you for doing some digging on this. 

A quick look at this after I have got home... This would require a change in the O365 library that the integration uses, that would take some time (it just always does).

I have someone else [reporting no todo lists](https://github.com/RogerSelwyn/O365-HomeAssistant/issues/250), which may or may not be related since they haven't responded to my queries. If it is the same problem, then it will likely warrant the work on the O365 library.

**Comment by williamg97** [comment]
Thanks for digging. I figured that would be the case. The workaround for now was to just manually take my list id's from the delta endpoint and manually update the yaml file.
