### ISSUE TITLE
Can not Authorize O365 from HA repair dialog (personal account)

### ISSUE THREAD

**Issue by ClearlyDazed** [RogerSelwyn/O365-HomeAssistant#256]
When activating the Link to O365 account, I can not log into Microsoft since I only have a personal account. It requires a work or school account. Everything else in the installation and configuration (simplified with and using the client value <
o365:
    accounts:
        - account_name: Outlook_Account
          client_id: !secret outlook_client_id
          client_secret: !secret outlook_client_secret>

I am only want to send emails. What next steps can I take, since Microsoft has tightened email account security?

**Comment by RogerSelwyn** [comment]
To be honest I'm not 100% aware of how personal accounts work in Entra/Azure since I don't use one, I just know that it used to work. If it still does I'm not sure.

Some things I would check. When you created the app did you select `Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)` for the supported accounts type. If you didn't I would doubt it would allow a personal account.

Also maybe look at this issue - https://github.com/RogerSelwyn/O365-HomeAssistant/issues/241

**Comment by ClearlyDazed** [comment]
Thank you for your help and this program. I changed Entra/Azure to use : Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox). This allowed my personal account to connect and setup. Notification emails are now sent from Home Assistant and received by Outlook.
