### ISSUE TITLE
Integration error: o365 - Integration 'o365' not found. - Even with version number.

### ISSUE THREAD

**Issue by technikly** [RogerSelwyn/O365-HomeAssistant#37]
Hi, I've read a lot of documentation on this and updated my manifest file and used older and newer versions of the manifest file. I still get this error message. Can anyone help? 

System: 

## System Health

version | core-2022.4.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.4.0-107-generic
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4772
Installed Version | 1.24.3
Stage | running
Available Repositories | 1006
Downloaded Repositories | 38

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 23 April 2022, 01:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-west-2-4.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Linux Mint 20.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.14
disk_total | 915.4 GB
disk_used | 122.8 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.0.1), AirCast (3.3.0), File editor (5.3.3), Check Home Assistant configuration (3.10.0), Zigbee2mqtt (1.22.2-1), Node-RED (11.1.1), Tautulli (2.3.0), eWeLink Smart Home (1.2.4), Home Assistant Google Drive Backup (0.106.2), Git pull (7.13.1), Grafana (7.5.2), Let's Encrypt (4.12.0), Home Panel (2.4.0), Samba share (9.5.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 18
views | 11
mode | storage

</details>

**Comment by RogerSelwyn** [comment]
Have you installed the O365 integration via HACS? Do you have an o365 folder inside your custom_components folder with a set of files matching this GitHub folder - https://github.com/RogerSelwyn/O365-HomeAssistant/tree/master/custom_components/o365

**Comment by technikly** [comment]
Thanks for the quick response. Yes installed via HACS. I also tried
manually installing and a prerelease version. All documentation seems to
match my installation.

**Comment by RogerSelwyn** [comment]
Does the below message appear in your log? If not, for some reason HA isn't recognising your install. I've seen this on occasion with other integrations installed via HACS and don't know the reason. It seems to resolve itself somehow, but I don't know the trigger. Another symptom is that it doesn't appear on the list on integrations on the Configuration/Settings/Info page. Any other errors in your logs?

`2022-04-09 09:56:38 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration o365 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

To be honest I don't believe this is an o365 integration problem, since there are 5-600 other installs of the integration. But I continue to learn.

**Comment by technikly** [comment]
No, that message didn't appear. I took out the yaml configuration entirely.
Reset HA. Then put it back in and suddenly it worked. So fixed!
Unfortunately, I then try and click on the config link and sign in. This
leads me to this

Could not locate token at /config/.O365-token-cache/o365.token
15:28:25 – (WARNING) Office 365 Calendar (custom integration)

I'm looking for the token anywhere but can't find it. I'm certain I am at
fault somewhere and haven't set things up properly somehow.

Thanks,

**Comment by RogerSelwyn** [comment]
That messages is telling you you aren't authenticated since it can't find the authentication token. Have you followed the authentication instructions here? - https://github.com/RogerSelwyn/O365-HomeAssistant#authentication

**Comment by technikly** [comment]
Yes, I believe so.

Web
Quickstart <https://portal.azure.com/#>
Docs <https://go.microsoft.com/fwlink/?linkid=2094259>
<https://portal.azure.com/#>
Redirect URIs
The URIs we will accept as destinations when returning authentication
responses (tokens) after successfully authenticating or signing out users.
The redirect URI you send in the request to the login server should match
one listed here. Also referred to as reply URLs. Learn more about Redirect
URIs and their restriction <https://go.microsoft.com/fwlink/?linkid=2094263>
<https://portal.azure.com/#>
ENTERED
<https://portal.azure.com/#>
Add URI <https://portal.azure.com/#>
Front-channel logout URL
This is where we send a request to have the application clear the user's
session data. This is required for single sign-out to work correctly.
P
Implicit grant and hybrid flows
Request a token directly from the authorization endpoint. If the
application has a single-page architecture (SPA) and doesn't use the
authorization code flow, or if it invokes a web API via JavaScript, select
both access tokens and ID tokens. For ASP.NET Core web apps and other web
apps that use hybrid authentication, select only ID tokens. Learn more
about tokens.
<https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-implicit-grant-flow?WT.mc_id=Portal-Microsoft_AAD_RegisteredApps>

Select the tokens you would like to be issued by the authorization endpoint:
Access tokens (used for implicit flows) (TICKED)
ID tokens (used for implicit and hybrid flows) (TICKED)
Supported account types
Who can use this application or access this API?

   - Accounts in this organizational directory only (XXXX only - Single
   tenant)
   - Accounts in any organizational directory (Any Azure AD directory -
   Multitenant) (TICKED)

Help me decide... <https://portal.azure.com/#>
Due to temporary differences in supported functionality, we don't recommend
enabling personal Microsoft accounts for an existing registration. If you
need to enable personal accounts, you can do so using the manifest
editor.  Learn
more about these restrictions.
<https://go.microsoft.com/fwlink/?linkid=2107401>
Starting November 9th, 2020 end users will no longer be able to grant
consent to newly registered multitenant apps without verified publishers.  Add
MPN ID to verify publisher <https://portal.azure.com/#>
Advanced settings
Allow public client flows
Enable the following mobile and desktop flows: YES

   - Yes
   - No


   - App collects plaintext password (Resource Owner Password Credential
   Flow) Learn more <https://go.microsoft.com/fwlink/?linkid=2144008>
   - No keyboard (Device Code Flow) Learn more
   <https://go.microsoft.com/fwlink/?linkid=2143943>
   - SSO for domain-joined Windows (Windows Integrated Auth Flow) Learn more
   <https://go.microsoft.com/fwlink/?linkid=2144007>

**Comment by technikly** [comment]
I also tried the alternative method, but this didn't work either. I'm at a
loss.

**Comment by RogerSelwyn** [comment]
It looks to me like the notification isn't working to request authentication. I'm trying to figure out why, as to whether it is something I broke, or it is something HA core broke.

**Comment by RogerSelwyn** [comment]
My error, it is fine. HA isn't adding a badge to the Notification menu item to show there is one. This seems to have changed with 2022.4. 

Sorry I can't follow the process you have written. Easiest method is to do the alt authentication method since it doesn't require access to your HA instance. So:
- Create app as defined in the installation method to get your client id and secret. 
  - Provide Name
  - Select the Any Org and Personal Accounts (or at least that is what I do, but you need to slect as appropriate for you) radio button
  - Add a web redirect uri as 'https://login.microsoftonline.com/common/oauth2/nativeclient' 
  - Copy the Application (client) ID
  - Create a New client secret with expiry as you like
  - Copy the **Value** of the client secret
- Configure o365 integration with the two values
```
o365:
  client_secret: !secret o365_secret
  client_id: !secret o365_id
```
- Restart your o365 instance
- Assuming you have configured correctly you will get an info message in the log saying there is no token so it is requesting authorisation
- Go to Notifications in HA and you should see a notification. Click on this.
- You will get a prompt to logon to O365
- You will get a permissions request, I tend to consent to this on behalf of my organisation. I'm sure there are multiple options but I'm no O365 expert. The instructions on the Github talks about setting these up beforehand, but doing it here works fine.
- Copy the url returned into the dialogue box in HA
- And you are done
- You may have to restart HA to get your calendar entities created

**Comment by RogerSelwyn** [comment]
I've literally just followed this process above because previously I just followed the process provided the original creator of the integration.

**Comment by technikly** [comment]
Thank you very much for your time! This worked in the end. I believe it was
the indenting which was off in config yaml. Lesson learned.
