### ISSUE TITLE
All-Day Events Start/End Time Off

### ISSUE THREAD

**Issue by mecarroll** [RogerSelwyn/O365-HomeAssistant#6]
The start and end time for all-day events are offset equal to the amount of time from GMT.  Adjusting start_offset in yaml file does not fix issue.

**Comment by RogerSelwyn** [comment]
I've spent some time looking at this problem this afternoon. I live in the UK, so it can be more of a problem diagnosing since this type of issue usually shows when you are outside UTC (which UK sort off isn't, well it is at the moment because we are on British Summer Time (BST) at +1).

I notice my normal events show at the right time, whilst my all day event shows 1 hour out, I guess because we are on BST.

I've been faking that I am in LA at -7 and the date/times being sent back to HA core all look to be formatted 'correctly' such at this for an 8am (UK) event shows as below, which comes up in my calendar at the right time.

`'start':{'dateTime': '2021-09-26T00:00:00-07:00'}`

My all day event has a start time as below, which then appears at 1am, but it is marked as all day

```
'start':{'dateTime': '2021-09-24T17:00:00-07:00'}
'is_all_day':True
```

I think logically it should be 16:00:00-07:00 for it to appear at midnight. That said, the O365 module that actually calls the MS services is returning this, so it looks like it is just returning what it has been passed.

`datetime.datetime(2021, 9, 24, 17, 0, tzinfo=<DstTzInfo 'America/Los_Angeles' PDT-1 day, 17:00:00 DST>)`

**Comment by RogerSelwyn** [comment]
So I think I need to do a little debugging on the O465 Pypi module (which is handled by someone else), to see what it is getting back from MS and why it is sending back based on a 'UTC' midnight for all day events.

I've done a bit of calendar stuff before (I did open source work on something call DotNetNuke), and all day events are a challenge... Are they midnight to midnight for anyone who looks at it, or only in the timezone they were created in (which is what I would expect)? So I'm not sure if MS are storing them as +1 (BST) or +0 (UTC or more likely GMT which implies BST during the summer).

It will take some digging....

**Comment by RogerSelwyn** [comment]
I've created this issue on the python-o365 module:

https://github.com/O365/python-o365/issues/690

**Comment by RogerSelwyn** [comment]
Potential fix - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v2.2.6b1

**Comment by RogerSelwyn** [comment]
Closed with - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v2.2.6
